### ISSUE TITLE
not an issue, but...

### ISSUE THREAD

**Issue by korewatori** [codecat/libflp#2]
just reading the source code now, how did you manage to pull someone's license data (mainly the license name)?
just thought I'd ask because i'm thinking of forking (with your approval) this repo + adding my own little touches to it.

**Comment by codecat** [comment]
It comes from the event `FLP_Text_Licensee`, which is a regular string except it's obfuscated. The code to deobfuscate it is in that event handler code as well.

Curious what you're gonna do with a fork! 👀

**Comment by korewatori** [comment]
I was thinking about adding parts of this to something bigger a few friends and I had an idea for. I could talk about it more but talking through GitHub issues isn't the best thing haha

**Comment by codecat** [comment]
Sounds interesting, but yes indeed, the issue tracker isn't the best place for this 👍
